server:
  port: 8080
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    name: comment
    url: jdbc:mysql://47.97.125.200:3306/comment?useUnicode=true&characterEncoding=UTF-8
    username: aiolos
    password: aiolosSQL1204285.
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    #true: 如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配，匹配不上和false一样被全局异常捕获
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    #接入前端静态资源页面
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
logging:
  level:
    com.aiolos.comment.dal: debug