server:
  tomcat:
    uri-encoding: UTF-8
  port: 8000
  ssl:
    key-store: ./src/main/resources/3105377_www.aiolosxhx.com.pfx
    key-store-password: mO3ClARB
    key-store-type: PKCS12
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  profiles:
    include:
    - jdbc
  datasource:
    name: comment
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  resources:
    #true: 如果所有的controller都没有命中，则使用默认的静态资源处理器做匹配，匹配不上和false一样被全局异常捕获
    add-mappings: true
  mvc:
    throw-exception-if-no-handler-found: true
    #接入前端静态资源页面
    static-path-pattern: /static/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 47.97.125.200
    port: 6379
    database: 8
    jedis:
      pool:
        max-active: 50
        min-idle: 20
logging:
  level:
    com.aiolos.comment.dal: debug
# 分布式文件系统fastdfs配置
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:
    width: 80
    height: 80
  tracker-list: 47.97.125.200:22122
image:
  url: https://www.aiolosxhx.com/aiolos/
#申明es服务地址
elasticsearch:
  ip: 127.0.0.1:9200