package com.aiolos.comment.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   活动评论消息回复表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_activity_comment_reply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class ActivityCommentReplyModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   活动ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.activity_id
     *
     * @mbg.generated
     */
    private Integer activityId;

    /**
     * Database Column Remarks:
     *   评论消息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.activity_comment_id
     *
     * @mbg.generated
     */
    private Integer activityCommentId;

    /**
     * Database Column Remarks:
     *   评论回复者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.from_uid
     *
     * @mbg.generated
     */
    private Integer fromUid;

    /**
     * Database Column Remarks:
     *   回复者昵称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   回复者头像，小头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     * Database Column Remarks:
     *   回复目标ID，也就是活动中的评论者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.to_uid
     *
     * @mbg.generated
     */
    private Integer toUid;

    /**
     * Database Column Remarks:
     *   回复状态，-2：被活动发起人删除，1：正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_activity_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.id
     *
     * @return the value of campus_activity_comment_reply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.id
     *
     * @param id the value for campus_activity_comment_reply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.activity_id
     *
     * @return the value of campus_activity_comment_reply.activity_id
     *
     * @mbg.generated
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.activity_id
     *
     * @param activityId the value for campus_activity_comment_reply.activity_id
     *
     * @mbg.generated
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.activity_comment_id
     *
     * @return the value of campus_activity_comment_reply.activity_comment_id
     *
     * @mbg.generated
     */
    public Integer getActivityCommentId() {
        return activityCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.activity_comment_id
     *
     * @param activityCommentId the value for campus_activity_comment_reply.activity_comment_id
     *
     * @mbg.generated
     */
    public void setActivityCommentId(Integer activityCommentId) {
        this.activityCommentId = activityCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.from_uid
     *
     * @return the value of campus_activity_comment_reply.from_uid
     *
     * @mbg.generated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.from_uid
     *
     * @param fromUid the value for campus_activity_comment_reply.from_uid
     *
     * @mbg.generated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.nickname
     *
     * @return the value of campus_activity_comment_reply.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.nickname
     *
     * @param nickname the value for campus_activity_comment_reply.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.head_portrait
     *
     * @return the value of campus_activity_comment_reply.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.head_portrait
     *
     * @param headPortrait the value for campus_activity_comment_reply.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.to_uid
     *
     * @return the value of campus_activity_comment_reply.to_uid
     *
     * @mbg.generated
     */
    public Integer getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.to_uid
     *
     * @param toUid the value for campus_activity_comment_reply.to_uid
     *
     * @mbg.generated
     */
    public void setToUid(Integer toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.status
     *
     * @return the value of campus_activity_comment_reply.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.status
     *
     * @param status the value for campus_activity_comment_reply.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_activity_comment_reply.gmt_create
     *
     * @return the value of campus_activity_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_activity_comment_reply.gmt_create
     *
     * @param gmtCreate the value for campus_activity_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}