package com.aiolos.comment.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   校报表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_information
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InformationModel {
    /**
     * Database Column Remarks:
     *   10位无符号数字，唯一自增长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   校报发起人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.from_uid
     *
     * @mbg.generated
     */
    private Integer fromUid;

    /**
     * Database Column Remarks:
     *   主题ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.topic_id
     *
     * @mbg.generated
     */
    private Integer topicId;

    /**
     * Database Column Remarks:
     *   省份
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     * Database Column Remarks:
     *   城市
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     * Database Column Remarks:
     *   县区
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.county
     *
     * @mbg.generated
     */
    private String county;

    /**
     * Database Column Remarks:
     *   是否为热门，0：不是热门，1：是热门
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.hot
     *
     * @mbg.generated
     */
    private Byte hot;

    /**
     * Database Column Remarks:
     *   点赞数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.thumbs_up_num
     *
     * @mbg.generated
     */
    private Integer thumbsUpNum;

    /**
     * Database Column Remarks:
     *   评论数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.comment_num
     *
     * @mbg.generated
     */
    private Integer commentNum;

    /**
     * Database Column Remarks:
     *   校报状态，-2：被强制关闭，-1：已删除，0：已发布，1：暂停，2：已结束
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   校报内容
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.id
     *
     * @return the value of campus_information.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.id
     *
     * @param id the value for campus_information.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.from_uid
     *
     * @return the value of campus_information.from_uid
     *
     * @mbg.generated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.from_uid
     *
     * @param fromUid the value for campus_information.from_uid
     *
     * @mbg.generated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.topic_id
     *
     * @return the value of campus_information.topic_id
     *
     * @mbg.generated
     */
    public Integer getTopicId() {
        return topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.topic_id
     *
     * @param topicId the value for campus_information.topic_id
     *
     * @mbg.generated
     */
    public void setTopicId(Integer topicId) {
        this.topicId = topicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.province
     *
     * @return the value of campus_information.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.province
     *
     * @param province the value for campus_information.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.city
     *
     * @return the value of campus_information.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.city
     *
     * @param city the value for campus_information.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.county
     *
     * @return the value of campus_information.county
     *
     * @mbg.generated
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.county
     *
     * @param county the value for campus_information.county
     *
     * @mbg.generated
     */
    public void setCounty(String county) {
        this.county = county == null ? null : county.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.hot
     *
     * @return the value of campus_information.hot
     *
     * @mbg.generated
     */
    public Byte getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.hot
     *
     * @param hot the value for campus_information.hot
     *
     * @mbg.generated
     */
    public void setHot(Byte hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.thumbs_up_num
     *
     * @return the value of campus_information.thumbs_up_num
     *
     * @mbg.generated
     */
    public Integer getThumbsUpNum() {
        return thumbsUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.thumbs_up_num
     *
     * @param thumbsUpNum the value for campus_information.thumbs_up_num
     *
     * @mbg.generated
     */
    public void setThumbsUpNum(Integer thumbsUpNum) {
        this.thumbsUpNum = thumbsUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.comment_num
     *
     * @return the value of campus_information.comment_num
     *
     * @mbg.generated
     */
    public Integer getCommentNum() {
        return commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.comment_num
     *
     * @param commentNum the value for campus_information.comment_num
     *
     * @mbg.generated
     */
    public void setCommentNum(Integer commentNum) {
        this.commentNum = commentNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.status
     *
     * @return the value of campus_information.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.status
     *
     * @param status the value for campus_information.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.gmt_create
     *
     * @return the value of campus_information.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.gmt_create
     *
     * @param gmtCreate the value for campus_information.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.gmt_modified
     *
     * @return the value of campus_information.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.gmt_modified
     *
     * @param gmtModified the value for campus_information.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information.content
     *
     * @return the value of campus_information.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information.content
     *
     * @param content the value for campus_information.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}