package com.aiolos.comment.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   校报评论消息回复表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_information_comment_reply
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InformationCommentReplyModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   校报ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.information_id
     *
     * @mbg.generated
     */
    private Integer informationId;

    /**
     * Database Column Remarks:
     *   评论消息ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.information_comment_id
     *
     * @mbg.generated
     */
    private Integer informationCommentId;

    /**
     * Database Column Remarks:
     *   评论回复者ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.from_uid
     *
     * @mbg.generated
     */
    private Integer fromUid;

    /**
     * Database Column Remarks:
     *   回复目标ID，也就是校报中的评论者
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.to_uid
     *
     * @mbg.generated
     */
    private Integer toUid;

    /**
     * Database Column Remarks:
     *   回复状态，-2：被校报发起人删除，1：正常
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.id
     *
     * @return the value of campus_information_comment_reply.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.id
     *
     * @param id the value for campus_information_comment_reply.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.information_id
     *
     * @return the value of campus_information_comment_reply.information_id
     *
     * @mbg.generated
     */
    public Integer getInformationId() {
        return informationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.information_id
     *
     * @param informationId the value for campus_information_comment_reply.information_id
     *
     * @mbg.generated
     */
    public void setInformationId(Integer informationId) {
        this.informationId = informationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.information_comment_id
     *
     * @return the value of campus_information_comment_reply.information_comment_id
     *
     * @mbg.generated
     */
    public Integer getInformationCommentId() {
        return informationCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.information_comment_id
     *
     * @param informationCommentId the value for campus_information_comment_reply.information_comment_id
     *
     * @mbg.generated
     */
    public void setInformationCommentId(Integer informationCommentId) {
        this.informationCommentId = informationCommentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.from_uid
     *
     * @return the value of campus_information_comment_reply.from_uid
     *
     * @mbg.generated
     */
    public Integer getFromUid() {
        return fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.from_uid
     *
     * @param fromUid the value for campus_information_comment_reply.from_uid
     *
     * @mbg.generated
     */
    public void setFromUid(Integer fromUid) {
        this.fromUid = fromUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.to_uid
     *
     * @return the value of campus_information_comment_reply.to_uid
     *
     * @mbg.generated
     */
    public Integer getToUid() {
        return toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.to_uid
     *
     * @param toUid the value for campus_information_comment_reply.to_uid
     *
     * @mbg.generated
     */
    public void setToUid(Integer toUid) {
        this.toUid = toUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.status
     *
     * @return the value of campus_information_comment_reply.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.status
     *
     * @param status the value for campus_information_comment_reply.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_comment_reply.gmt_create
     *
     * @return the value of campus_information_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_comment_reply.gmt_create
     *
     * @param gmtCreate the value for campus_information_comment_reply.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }
}