package com.aiolos.comment.model;

import java.util.Date;

/**
 * Database Table Remarks:
 *   校报主题表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_information_topic
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class InformationTopicModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   主题名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.topic_name
     *
     * @mbg.generated
     */
    private String topicName;

    /**
     * Database Column Remarks:
     *   主题状态，-1：已删除，0：待审核，1：已发布
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.status
     *
     * @mbg.generated
     */
    private Byte status;

    /**
     * Database Column Remarks:
     *   主题类型，0：普通话题，1：活动主题(有状态)
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.type
     *
     * @mbg.generated
     */
    private Byte type;

    /**
     * Database Column Remarks:
     *   排序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_information_topic.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.id
     *
     * @return the value of campus_information_topic.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.id
     *
     * @param id the value for campus_information_topic.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.topic_name
     *
     * @return the value of campus_information_topic.topic_name
     *
     * @mbg.generated
     */
    public String getTopicName() {
        return topicName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.topic_name
     *
     * @param topicName the value for campus_information_topic.topic_name
     *
     * @mbg.generated
     */
    public void setTopicName(String topicName) {
        this.topicName = topicName == null ? null : topicName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.status
     *
     * @return the value of campus_information_topic.status
     *
     * @mbg.generated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.status
     *
     * @param status the value for campus_information_topic.status
     *
     * @mbg.generated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.type
     *
     * @return the value of campus_information_topic.type
     *
     * @mbg.generated
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.type
     *
     * @param type the value for campus_information_topic.type
     *
     * @mbg.generated
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.sort
     *
     * @return the value of campus_information_topic.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.sort
     *
     * @param sort the value for campus_information_topic.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.gmt_create
     *
     * @return the value of campus_information_topic.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.gmt_create
     *
     * @param gmtCreate the value for campus_information_topic.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_information_topic.gmt_modified
     *
     * @return the value of campus_information_topic.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_information_topic.gmt_modified
     *
     * @param gmtModified the value for campus_information_topic.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}