package com.aiolos.comment.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Database Table Remarks:
 *   用户表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table campus_user
 *
 * @mbg.generated do_not_delete_during_merge
 */
public class UserModel implements Serializable {
    /**
     * Database Column Remarks:
     *   10位无符号数字，唯一自增长
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   系统生成的唯一ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.account_id
     *
     * @mbg.generated
     */
    private Integer accountId;

    /**
     * Database Column Remarks:
     *   昵称，唯一
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.nickname
     *
     * @mbg.generated
     */
    private String nickname;

    /**
     * Database Column Remarks:
     *   手机号，默认的注册账号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.telphone
     *
     * @mbg.generated
     */
    private String telphone;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * Database Column Remarks:
     *   邮箱
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     * Database Column Remarks:
     *   用户头像，小头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.head_portrait
     *
     * @mbg.generated
     */
    private String headPortrait;

    /**
     * Database Column Remarks:
     *   用户头像，大头像
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.head_portrait_big
     *
     * @mbg.generated
     */
    private String headPortraitBig;

    /**
     * Database Column Remarks:
     *   关注数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.follows
     *
     * @mbg.generated
     */
    private Integer follows;

    /**
     * Database Column Remarks:
     *   被关注数
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.concerns
     *
     * @mbg.generated
     */
    private Integer concerns;

    /**
     * Database Column Remarks:
     *   积分，通过签到和活动增加，发布活动和置顶时消耗
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.credit
     *
     * @mbg.generated
     */
    private Integer credit;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.gmt_create
     *
     * @mbg.generated
     */
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column campus_user.gmt_modified
     *
     * @mbg.generated
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.id
     *
     * @return the value of campus_user.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.id
     *
     * @param id the value for campus_user.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.account_id
     *
     * @return the value of campus_user.account_id
     *
     * @mbg.generated
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.account_id
     *
     * @param accountId the value for campus_user.account_id
     *
     * @mbg.generated
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.nickname
     *
     * @return the value of campus_user.nickname
     *
     * @mbg.generated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.nickname
     *
     * @param nickname the value for campus_user.nickname
     *
     * @mbg.generated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.telphone
     *
     * @return the value of campus_user.telphone
     *
     * @mbg.generated
     */
    public String getTelphone() {
        return telphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.telphone
     *
     * @param telphone the value for campus_user.telphone
     *
     * @mbg.generated
     */
    public void setTelphone(String telphone) {
        this.telphone = telphone == null ? null : telphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.password
     *
     * @return the value of campus_user.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.password
     *
     * @param password the value for campus_user.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.email
     *
     * @return the value of campus_user.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.email
     *
     * @param email the value for campus_user.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.head_portrait
     *
     * @return the value of campus_user.head_portrait
     *
     * @mbg.generated
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.head_portrait
     *
     * @param headPortrait the value for campus_user.head_portrait
     *
     * @mbg.generated
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.head_portrait_big
     *
     * @return the value of campus_user.head_portrait_big
     *
     * @mbg.generated
     */
    public String getHeadPortraitBig() {
        return headPortraitBig;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.head_portrait_big
     *
     * @param headPortraitBig the value for campus_user.head_portrait_big
     *
     * @mbg.generated
     */
    public void setHeadPortraitBig(String headPortraitBig) {
        this.headPortraitBig = headPortraitBig == null ? null : headPortraitBig.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.follows
     *
     * @return the value of campus_user.follows
     *
     * @mbg.generated
     */
    public Integer getFollows() {
        return follows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.follows
     *
     * @param follows the value for campus_user.follows
     *
     * @mbg.generated
     */
    public void setFollows(Integer follows) {
        this.follows = follows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.concerns
     *
     * @return the value of campus_user.concerns
     *
     * @mbg.generated
     */
    public Integer getConcerns() {
        return concerns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.concerns
     *
     * @param concerns the value for campus_user.concerns
     *
     * @mbg.generated
     */
    public void setConcerns(Integer concerns) {
        this.concerns = concerns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.credit
     *
     * @return the value of campus_user.credit
     *
     * @mbg.generated
     */
    public Integer getCredit() {
        return credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.credit
     *
     * @param credit the value for campus_user.credit
     *
     * @mbg.generated
     */
    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.gmt_create
     *
     * @return the value of campus_user.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.gmt_create
     *
     * @param gmtCreate the value for campus_user.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column campus_user.gmt_modified
     *
     * @return the value of campus_user.gmt_modified
     *
     * @mbg.generated
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column campus_user.gmt_modified
     *
     * @param gmtModified the value for campus_user.gmt_modified
     *
     * @mbg.generated
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}