package com.aiolos.comment.dal;

import com.aiolos.comment.model.ActivityThumbsUpModel;

public interface ActivityThumbsUpModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    int insert(ActivityThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    int insertSelective(ActivityThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    ActivityThumbsUpModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityThumbsUpModel record);

    int selectByModel(ActivityThumbsUpModel record);

    int cancelThumbsUp(ActivityThumbsUpModel record);
}