package com.aiolos.comment.dal;

import com.aiolos.comment.model.ActivityCommentModel;

public interface ActivityCommentModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    int insert(ActivityCommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    int insertSelective(ActivityCommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    ActivityCommentModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityCommentModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityCommentModel record);
}