package com.aiolos.comment.dal;

import com.aiolos.comment.model.ActivityImagesModel;

public interface ActivityImagesModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    int insert(ActivityImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    int insertSelective(ActivityImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    ActivityImagesModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityImagesModel record);
}