package com.aiolos.comment.dal;

import com.aiolos.comment.model.ActivityCommentReplyModel;

public interface ActivityCommentReplyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    int insert(ActivityCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    int insertSelective(ActivityCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    ActivityCommentReplyModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ActivityCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_activity_comment_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ActivityCommentReplyModel record);
}