package com.aiolos.comment.dal;

import com.aiolos.comment.model.ConcernRelationModel;

import java.util.List;

public interface ConcernRelationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    int insert(ConcernRelationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    int insertSelective(ConcernRelationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    ConcernRelationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConcernRelationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_concern_relation
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConcernRelationModel record);

    int cancelFollow(ConcernRelationModel record);

    List<Integer> selectByConcernUid(Integer userId);

    int selectByModel(ConcernRelationModel record);
}