package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationCommentReplyModel;

public interface InformationCommentReplyModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    int insert(InformationCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    int insertSelective(InformationCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    InformationCommentReplyModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationCommentReplyModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_reply
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationCommentReplyModel record);
}