package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationTopicModel;

import java.util.List;

public interface InformationTopicModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    int insert(InformationTopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    int insertSelective(InformationTopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    InformationTopicModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationTopicModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_topic
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationTopicModel record);

    List<InformationTopicModel> selectAllTopics();
}