package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationModel;
import com.aiolos.comment.vo.InformationVO;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface InformationModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int insert(InformationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int insertSelective(InformationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    InformationModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(InformationModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationModel record);

    List<InformationVO> selectAllInformation(@Param("topicId") int topicId, @Param("pageIndex") int pageIndex, @Param("pageCount") int pageCount);

    int increaseThumbsUp(int id);

    int decreaseThumbsUp(int id);

    int increaseComment(int id);
}