package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationThumbsUpModel;

public interface InformationThumbsUpModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    int insert(InformationThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    int insertSelective(InformationThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    InformationThumbsUpModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationThumbsUpModel record);

    int selectByModel(InformationThumbsUpModel record);

    int cancelThumbsUp(InformationThumbsUpModel record);
}