package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationCommentThumbsUpModel;

public interface InformationCommentThumbsUpModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    int insert(InformationCommentThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    int insertSelective(InformationCommentThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    InformationCommentThumbsUpModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationCommentThumbsUpModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_comment_thumbs_up
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationCommentThumbsUpModel record);
}