package com.aiolos.comment.dal;

import com.aiolos.comment.model.InformationImagesModel;

public interface InformationImagesModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    int insert(InformationImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    int insertSelective(InformationImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    InformationImagesModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(InformationImagesModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_information_images
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(InformationImagesModel record);
}