package com.aiolos.comment.dal;

import com.aiolos.comment.model.UserModel;
import org.apache.ibatis.annotations.Param;

public interface UserModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int insert(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int insertSelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    UserModel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table campus_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserModel record);

    UserModel selectByTelphoneAndPassword(@Param("telphone") String telphone, @Param("password") String password);

    int getUserCountByTelphone(UserModel record);

    UserModel getUserByTelphone(String telphone);

    int increaseFollows(int id);

    int decreaseFollows(int id);

    int increaseConcerns(int id);

    int decreaseConcerns(int id);
}